name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    name: macOS (Build & Test)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -v
      - name: Test
        run: swift test -v

  ios:
    name: iOS (Build & Test)
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: List available simulators
        run: |
          xcrun simctl list devices
          xcodebuild -showsdks
      - name: Build
        run: xcodebuild build -scheme TPInAppReceipt -destination 'platform=iOS Simulator,OS=latest,name=iPhone 17' -skipPackagePluginValidation SWIFT_STRICT_CONCURRENCY=targeted
      - name: Test
        run: xcodebuild test -scheme TPInAppReceipt -destination 'platform=iOS Simulator,OS=latest,name=iPhone 17' -skipPackagePluginValidation SWIFT_STRICT_CONCURRENCY=targeted

  catalyst:
    name: Mac Catalyst (Build & Test)
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build -scheme TPInAppReceipt -destination 'platform=macOS,variant=Mac Catalyst' -skipPackagePluginValidation SWIFT_STRICT_CONCURRENCY=targeted
      - name: Test
        run: xcodebuild test -scheme TPInAppReceipt -destination 'platform=macOS,variant=Mac Catalyst' -skipPackagePluginValidation SWIFT_STRICT_CONCURRENCY=targeted
